# Generated by Django 4.0.3 on 2023-03-15 11:55

from django.db import migrations, models
import django.db.models.deletion
import viz.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VizNodeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VizNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(default=viz.models.one_workday_hence)),
                ('viznode_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viz.viznodelist')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
